### ISSUE TITLE
feat request: configurable timer [low priority]

### ISSUE THREAD

**Issue by dhulihan** [qualidafial/pomo#1]
Sometimes i'm in low-focus mode and I use 15 minute pomo sessions instead of 25 (I acknowledge this somewhat defeats the purpose of pomodoro), but it would be cool to have a configurable default timer in a config file. Not high priority.

**Comment by qualidafial** [comment]
Fixed on the main branch. Pomodoro timers may be configured by editing `~/.pomo/config.yaml`, which `pomo` now auto-generates if it does not exist:

```yaml
timer:
    break: 5m
    long-break: 15m
    pomodoro: 25m
```
